"""Added Faculty Table

Revision ID: 1350d78d2280
Revises: 7f41ae65481f
Create Date: 2026-05-08 14:06:45.481558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1350d78d2280'
down_revision: Union[str, Sequence[str], None] = '7f41ae65481f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('faculty_name', sa.VARCHAR(), nullable=False),
    sa.Column('university_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['university_name'], ['university.university_name'], ),
    sa.PrimaryKeyConstraint('faculty_name')
    )
    op.create_unique_constraint(None, 'courses', ['course_id'])
    op.add_column('department', sa.Column('faculty_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'department', ['department_name'])
    op.create_foreign_key(None, 'department', 'faculty', ['faculty_name'], ['faculty_name'])
    op.create_unique_constraint(None, 'university', ['university_name'])
    op.add_column('users', sa.Column('faculty_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_foreign_key(None, 'users', 'faculty', ['faculty_name'], ['faculty_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'faculty_name')
    op.drop_constraint(None, 'university', type_='unique')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_constraint(None, 'department', type_='unique')
    op.drop_column('department', 'faculty_name')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_table('faculty')
    # ### end Alembic commands ###
