"""Changed Foreign Keys

Revision ID: 3fb45fe274a1
Revises: b78b57ebec61
Create Date: 2026-05-08 16:09:48.671492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3fb45fe274a1'
down_revision: Union[str, Sequence[str], None] = 'b78b57ebec61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('university_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('university_name', sa.VARCHAR(), nullable=False),
    sa.Column('university_abbreviation', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('university_id'),
    sa.UniqueConstraint('university_abbreviation'),
    sa.UniqueConstraint('university_name')
    )
    op.create_table('faculty',
    sa.Column('faculty_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('faculty_name', sa.VARCHAR(), nullable=True),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['university.university_id'], ),
    sa.PrimaryKeyConstraint('faculty_id')
    )
    op.create_table('department',
    sa.Column('department_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.VARCHAR(), nullable=True),
    sa.Column('department_abbreviation', sa.VARCHAR(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_abbreviation'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.VARCHAR(), nullable=False),
    sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credit_unit', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_id')
    )
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('matric_number', sa.VARCHAR(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('is_course_rep', sa.BOOLEAN(), nullable=True),
    sa.Column('rep_status', sa.VARCHAR(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.faculty_id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['university.university_id'], ),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matric_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('courses')
    op.drop_table('department')
    op.drop_table('faculty')
    op.drop_table('university')
    # ### end Alembic commands ###
