"""New Models Added

Revision ID: 7f41ae65481f
Revises: 
Create Date: 2026-05-07 21:19:41.880102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f41ae65481f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('university_name', sa.VARCHAR(), nullable=False),
    sa.Column('university_abbreviation', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('university_name'),
    sa.UniqueConstraint('university_abbreviation'),
    sa.UniqueConstraint('university_name')
    )
    op.create_table('department',
    sa.Column('department_name', sa.VARCHAR(), nullable=False),
    sa.Column('department_abbreviation', sa.VARCHAR(), nullable=True),
    sa.Column('university_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['university_name'], ['university.university_name'], ),
    sa.PrimaryKeyConstraint('department_name'),
    sa.UniqueConstraint('department_abbreviation'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.VARCHAR(), nullable=False),
    sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credit_unit', sa.Integer(), nullable=False),
    sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('university_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['department_name'], ['department.department_name'], ),
    sa.ForeignKeyConstraint(['university_name'], ['university.university_name'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_id')
    )
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('matric_number', sa.VARCHAR(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('is_course_rep', sa.BOOLEAN(), nullable=True),
    sa.Column('rep_status', sa.VARCHAR(), nullable=True),
    sa.Column('university_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['department_name'], ['department.department_name'], ),
    sa.ForeignKeyConstraint(['university_name'], ['university.university_name'], ),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matric_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('courses')
    op.drop_table('department')
    op.drop_table('university')
    # ### end Alembic commands ###
