"""Make abbreviation not unique for departments

Revision ID: 8b125178b7a4
Revises: a803c829f73e
Create Date: 2026-05-12 20:34:52.830288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b125178b7a4'
down_revision: Union[str, Sequence[str], None] = 'a803c829f73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('department_department_abbreviation_key'), 'department', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('department_department_abbreviation_key'), 'department', ['department_abbreviation'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
