"""Added FK to university

Revision ID: 93f4267b2a25
Revises: 3fb45fe274a1
Create Date: 2026-05-11 13:15:02.518182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93f4267b2a25'
down_revision: Union[str, Sequence[str], None] = '3fb45fe274a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courses', ['course_id'])
    op.add_column('university', sa.Column('faculty_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'university', 'faculty', ['faculty_id'], ['faculty_id'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'university', type_='foreignkey')
    op.drop_column('university', 'faculty_id')
    op.drop_constraint(None, 'courses', type_='unique')
    # ### end Alembic commands ###
