"""Removed faculty_id from University Table

Revision ID: a803c829f73e
Revises: 93f4267b2a25
Create Date: 2026-05-12 20:05:56.418491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a803c829f73e"
down_revision: Union[str, Sequence[str], None] = "93f4267b2a25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("university_faculty_id_fkey"), "university", type_="foreignkey"
    )
    op.drop_column("university", "faculty_id")
    op.add_column("users", sa.Column("course_id", sa.String(), nullable=False))
    op.create_foreign_key(None, "users", "courses", ["course_id"], ["course_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "course_id")
    op.add_column(
        "university",
        sa.Column("faculty_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("university_faculty_id_fkey"),
        "university",
        "faculty",
        ["faculty_id"],
        ["faculty_id"],
    )
    # ### end Alembic commands ###
