"""Added new things

Revision ID: b9afad47152c
Revises: 8b125178b7a4
Create Date: 2026-05-13 17:24:17.607153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9afad47152c'
down_revision: Union[str, Sequence[str], None] = '8b125178b7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercourse',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('course_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('level', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'department', ['department_id'], ['department_id'])
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('users_course_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'department', ['department_id'], ['department_id'])
    op.drop_column('users', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('course_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_course_id_fkey'), 'users', 'courses', ['course_id'], ['course_id'])
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'level')
    op.drop_table('usercourse')
    # ### end Alembic commands ###
