"""first migration

Revision ID: e944b4818b5e
Revises:
Create Date: 2025-12-24 17:38:41.815412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e944b4818b5e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column("course_code", sa.VARCHAR(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("department", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("date_uploaded", sa.DATE(), nullable=True),
        sa.Column("uploaded_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("course_code"),
    )
    op.add_column("courses", sa.Column("level", sa.Integer(), nullable=True))
    op.alter_column(
        "courses",
        "course_code",
        existing_type=sa.TEXT(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "courses",
        "course_code",
        existing_type=sa.VARCHAR(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("courses", "level")
    op.drop_table("notes")
    # ### end Alembic commands ###
