"""Changed Fks

Revision ID: ef9a7e6a43f4
Revises: 1350d78d2280
Create Date: 2026-05-08 15:51:56.761378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef9a7e6a43f4'
down_revision: Union[str, Sequence[str], None] = '1350d78d2280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('courses_university_name_fkey'), 'courses', type_='foreignkey')
    op.drop_constraint(op.f('courses_department_name_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'department', ['department_id'], ['department_id'])
    op.drop_column('courses', 'university_name')
    op.drop_column('courses', 'department_name')
    op.add_column('department', sa.Column('department_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('department', sa.Column('faculty_id', sa.Integer(), nullable=False))
    op.alter_column('department', 'department_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('department_faculty_name_fkey'), 'department', type_='foreignkey')
    op.drop_constraint(op.f('department_university_name_fkey'), 'department', type_='foreignkey')
    op.create_foreign_key(None, 'department', 'faculty', ['faculty_id'], ['faculty_id'])
    op.drop_column('department', 'faculty_name')
    op.drop_column('department', 'university_name')
    op.add_column('faculty', sa.Column('faculty_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('faculty', sa.Column('university_id', sa.Integer(), nullable=False))
    op.alter_column('faculty', 'faculty_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('faculty_university_name_fkey'), 'faculty', type_='foreignkey')
    op.create_foreign_key(None, 'faculty', 'university', ['university_id'], ['university_id'])
    op.drop_column('faculty', 'university_name')
    op.add_column('university', sa.Column('university_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('faculty_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('university_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('users_faculty_name_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_university_name_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_department_name_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'department', ['department_id'], ['department_id'])
    op.create_foreign_key(None, 'users', 'university', ['university_id'], ['university_id'])
    op.create_foreign_key(None, 'users', 'faculty', ['faculty_id'], ['faculty_id'])
    op.drop_column('users', 'faculty_name')
    op.drop_column('users', 'university_name')
    op.drop_column('users', 'department_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('university_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('faculty_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_department_name_fkey'), 'users', 'department', ['department_name'], ['department_name'])
    op.create_foreign_key(op.f('users_university_name_fkey'), 'users', 'university', ['university_name'], ['university_name'])
    op.create_foreign_key(op.f('users_faculty_name_fkey'), 'users', 'faculty', ['faculty_name'], ['faculty_name'])
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'university_id')
    op.drop_column('users', 'faculty_id')
    op.drop_column('university', 'university_id')
    op.add_column('faculty', sa.Column('university_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'faculty', type_='foreignkey')
    op.create_foreign_key(op.f('faculty_university_name_fkey'), 'faculty', 'university', ['university_name'], ['university_name'])
    op.alter_column('faculty', 'faculty_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('faculty', 'university_id')
    op.drop_column('faculty', 'faculty_id')
    op.add_column('department', sa.Column('university_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('department', sa.Column('faculty_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.create_foreign_key(op.f('department_university_name_fkey'), 'department', 'university', ['university_name'], ['university_name'])
    op.create_foreign_key(op.f('department_faculty_name_fkey'), 'department', 'faculty', ['faculty_name'], ['faculty_name'])
    op.alter_column('department', 'department_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('department', 'faculty_id')
    op.drop_column('department', 'department_id')
    op.add_column('courses', sa.Column('department_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('university_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_department_name_fkey'), 'courses', 'department', ['department_name'], ['department_name'])
    op.create_foreign_key(op.f('courses_university_name_fkey'), 'courses', 'university', ['university_name'], ['university_name'])
    op.drop_column('courses', 'department_id')
    # ### end Alembic commands ###
